### ISSUE TITLE
поставил модуль - словил глюк интерфейса

### ISSUE THREAD

**Issue by jorjik** [webber12/eFilter#2]
http://SSMaker.ru/a73d4ed0/

+ не очень понятно как делать пункт "5": &param_cat_id=ID категории параметров
** я создал шаблон такой
и присвоил ему нужные TV (но глюк был и ранее)

Да, вот ещё в логах нашёл
```
« Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY `rank` ASC, `caption` ASC' at line 1 »
SQL > SELECT `id`,`caption` FROM `im`.`modx_site_tmplvars` WHERE `category` IN () ORDER BY `rank` ASC, `caption` ASC
```

**Comment by jorjik** [comment]
Так - разобрался небыло "взаимного" импорта

но теперь не ясно как настроить http://SSMaker.ru/83486cd5/ ?

**Comment by webber12** [comment]
Что именно неясно тут http://SSMaker.ru/83486cd5/ ? Выбрать из списка те параметры, которые будут участвовать в фильтрации (из группы параметров param_cat_id (который вы задали на предыдущем шаге) и сохранить :)

**Comment by jorjik** [comment]
а у меня там нет опций для выбора :(

**Comment by jorjik** [comment]
достаточно ли добавить в "param_cat_id" узел (2) если у меня такая структура http://SSMaker.ru/2039f730/ ?

**Comment by webber12** [comment]
ID категории параметров - это id категории tv-параметров, которые мы будем использовать для фильтрации. Т.е. делаем категорию вроде "параметры товара" - и туда помещаем все tv, которые нам нужны для фильтров. id этой категории в конфиг и надо вносить - дерево тут вообще ни при чем. Вот эти категории - https://yadi.sk/i/vY6ZWbPUf8HPx
Ну и не забыть в сниппете multiParams сделать импорт/экспорт общих параметров из модуля.

**Comment by jorjik** [comment]
создал категорию http://SSMaker.ru/08f0d97c/
но где смотреть eё ID ?

**Comment by webber12** [comment]
в базе или в любом "просмотре кода исходного элемента" - https://yadi.sk/i/hZVHP3XLf8UaV )))
