### ISSUE TITLE
Обёртка группы

### ISSUE THREAD

**Issue by 0test** [webber12/eFilter#27]
Было бы очень круто, если бы можно было задать обёртку группы параметров в фильтре.
Сам не смог(

**Comment by webber12** [comment]
Что-то я не совсем понял о какой группе речь и чем она отличается от существующей "категории" :)

**Comment by 0test** [comment]
Когда товары объединяем в группу, он автоматически делает вот [это](https://github.com/webber12/eFilter/blob/5b0ff6186c4124caa021f01a9109be5e77e95741/assets/snippets/eFilter/eFilter.class.php#L196)
`$output .= '<div class="eFiltr_cat eFiltr_cat' . $fc . ' ' . $filterCatClass . '">';`
А хотелось бы задать для группы именно **свой** шаблон вывода, с указанием, где будет wrapper и прочим. Надеюсь, понятно объяснил.

**Comment by 0test** [comment]
Да задача-то как раз стандартная. Вот допустим кусок бутстрапа, где пришлось вставлять в код обёртку ```$output .= '<ul class="list-group">';```
```
<form id="eFiltr" class="eFiltr eFiltr_form" action="/womans/" method="get">
	<div class="eFiltr_cat eFiltr_cat0 panel panel-default">
		<div class="panel-heading">Параметры</div>
		<ul class="list-group">
			<li class="list-group-item">
				<h4 class="list-group-item-heading">Размеры</h4>
				<select name="f[13][]" class="form-control input-sm">
					<option value="0"> - Размеры - </option>
					<option value="L">L (5)</option><option value="M">M (1)</option><option value="S">S (1)</option><option value="XL">XL (3)</option><option value="XS">XS (5)</option><option value="XXL">XXL (2)</option>
				</select>
			</li>

			<li class="list-group-item">
					<h4 class="list-group-item-heading">Цвет</h4>
				<div class="radio">
					<label>
						<input type="radio" name="f[11][]" value="0">Все товары
				  </label> 
				</div>
				<div class="radio">
					<label>
						<input type="radio" name="f[11][]" value="Белый">Белый<span class="badge">3</span>
				  </label> 
				</div>
			</li>
		</ul>
	</div>
	<div class="eFiltr_cat eFiltr_cat1 panel panel-default">
		<div class="panel-heading">Дополнительно</div>
		<ul class="list-group">
			<li class="list-group-item">
				<h4 class="list-group-item-heading">Тип ткани</h4>			
				<div class="checkbox-input">
					<label class="checkbox ">
						<input type="checkbox" name="f[14][]" value="Батик">Батик<span class="badge">1</span>
					</label>
				</div>	

				<div class="checkbox-input">
					<label class="checkbox ">
						<input type="checkbox" name="f[14][]" value="Фланель">Фланель<span class="badge">1</span>
					</label>
				</div>
			</li>

			<li class="list-group-item">
				<h4 class="list-group-item-heading">Узор</h4>	
				<div class="checkbox-input">
				<label class="checkbox  ">
					<input type="checkbox" name="f[17][]" value="ic_filter_color1.png"> <img src="assets/images/pattern/ic_filter_color1.png" alt=""> Красненький <span class="badge">2</span>
				</label>
				</div>	

				<div class="checkbox-input">
				<label class="checkbox  ">
					<input type="checkbox" name="f[17][]" value="ic_filter_color2.png"> <img src="assets/images/pattern/ic_filter_color2.png" alt=""> Синенький <span class="badge">2</span>
				</label>
				</div>
			</li>		
		</ul>
	</div>
</form>```

**Comment by webber12** [comment]
Попробуй так https://github.com/webber12/eFilter/commit/36e82aa30aa67945c5c94bb0681bb8fd764389d5 - негде потестить :)

**Comment by 0test** [comment]
Просто шикарно, спасибо. Теперь можно стилизовать фильтры вообще как угодно. Попробовал на обучающем сайте сделать, всё арбай. http://lesson.1px.su/womans/
Соответственно, предыдущие коммиты с классом теперь не нужны)

**Comment by webber12** [comment]
Ок, подождем, вдруг еще какие косяки повылазят.
Кстати, для отключения в режиме ajax=1 изменений в $_GET-строке уже давно есть параметр &changeState=`0` (вроде даже рабочий) . Тебя жt вроде смущала эта строка с %% ))

**Comment by 0test** [comment]
Возможно &changeState=0 давно добавлен, у меня не сработал, нужно обновиться. Подожду пуша с tplOuterCategory  и сразу уж..
