### ISSUE TITLE
Ошибк при использовании модуля для значений

### ISSUE THREAD

**Issue by Typodin** [webber12/eFilter#4]
Установил и настроил фильтр, добавил значения через модуль: http://joxi.ru/823bxX6fBRBOmO  вставил код в параметр и вывел на сайте. При использовании типа внешнего фильтра селект, все корректно выводит. 

Но при использовании Диапазона или Слайдера получаю значение от -1 до 1:
http://joxi.ru/Q2KVYolI8Bk3mj

Специально создал еще один тип с текстовым вводом в ресурсе, вывел как слайдер, все корректно. Также проверил вручную добавив значения, вместо @EVAL return $modx->runSnippet("multiParams", array("parent"=>"1"));  просто ввел в тв 3||4||5||6 - также все корректно отрабатывает. То есть именно модуль дал ошибку.

**Comment by webber12** [comment]
При выбранных двух чекбоксах, даже один из них был пустой - не может посчитать min и max значение. Отсюда эти значения 0, и диапазон -1 .. +1. Для слайдера и диапазона должно быть единственное числовое значение и никаких || в базе.
