### ISSUE TITLE
Touch support for range slider

### ISSUE THREAD

**Issue by Nicola1971** [webber12/eFilter#5]
jQuery UI range slider does not work on mobile devices.
Can you add jquery-ui-touch-punch?
https://github.com/furf/jquery-ui-touch-punch

http://fellowtuts.com/jquery/jquery-ui-sliders-on-touch-devices/

**Comment by webber12** [comment]
done https://github.com/webber12/eFilter/commit/4142d6f359b5bae4082c74f560618d3af8e52a4d

**Comment by Nicola1971** [comment]
Does it works for you?
I've tested on my ipad4 and my Android Phone, but does nothing :(

**Comment by webber12** [comment]
Sorry, ones more small fix - https://github.com/webber12/eFilter/commit/e4273beb72ab4ef789dda225f124a07d397cb6f8
:)
I`ve tested on my android phone - now it works correctly for me.

**Comment by Nicola1971** [comment]
Ok, Now it's  more touch friendly: I can "tap" to set the slider range but i can't "drag" like:

http://refreshless.com/nouislider/

http://ionden.com/a/plugins/ion.rangeSlider/en.html

Is jQuery UI used in other parts of the plugin as well the rangeslider?

**Comment by webber12** [comment]
In this project jQuery UI is used only for slider. But in my tests on andro-phone both "tapping" and "dragging" work correctly. May be some js-cashing problem or ipad/ios-only problem in your case?
