### ISSUE TITLE
В версии 1.1b-d7.1.3 не подключаются js и css

### ISSUE THREAD

**Issue by Typodin** [webber12/eFilter#6]
В сборке от Димы В 1.1b-d7.1.3 не подключаются js и css при вызове фильтра. При этом, если прописать подключение стилей и скриптов вручную в шапку, то все прекрасно работает. В 1.1b-d7.1.2 такой проблемы не было.

**Comment by webber12** [comment]
Может там какой косяк по верстке? Например, нет открывающего и закрывающего тегов <head> </head> :)

Если подключить стили и скрипты отдельным сниппетом такого плана (вызвать перед вызовом фильтра), тоже не работает?

```
<?php
$modx->regClientCSS('assets/snippets/eFilter/html/css/eFilter.css');
$modx->regClientCSS('assets/snippets/eFilter/html/css/slider.css');
$modx->regClientStartupScript('assets/snippets/eFilter/html/js/jquery-ui.min.js');
$modx->regClientStartupScript('assets/snippets/eFilter/html/js/jquery.ui.touch-punch.min.js');
if (isset($params['ajax']) && $params['ajax'] == '1') {
    $modx->regClientStartupScript('<script>var eFiltrAjax = "1";</script>', array('plaintext' => true));
}
if (!isset($params['autoSubmit']) || $params['autoSubmit'] == '1') {
    $modx->regClientStartupScript('<script>var eFiltrAutoSubmit = "1";</script>', array('plaintext' => true));
}
$modx->regClientStartupScript('assets/snippets/eFilter/html/js/eFilter.js');
?>
```

**Comment by Typodin** [comment]
Подключил отдельным сниппетом - не работает.

**Comment by webber12** [comment]
Ну значит надо там поискать отличия в методах $modx->regClientCSS и  $modx->regClientStartupScript . Я пока эту версию не ставил, так что сказать ничего не могу - раньше это были стандартные методы подключения скриптов и стилей в шапку и они работали :)

**Comment by Typodin** [comment]
Все же какая-то фигня происходит, буду построчно перебирать верстку, поставил на другой сайт, все нормально работает.
