### ISSUE TITLE
Неправильный результат при частичном совпадении названия

### ISSUE THREAD

**Issue by Typodin** [webber12/eFilter#7]
В фильтрации стоят модели автомобилей разных классов. Если мы выбираем любой класс, кроме A, то выдает все резульртаты корректно. Если выбираем А, то выдает и вариант с А и вариант с CLA: http://joxi.ru/l2Z1Robf8DlkQm

Юмора ради добавил еще вариант DMB-klasse и он начал выдаваться вместе с B-klasse: http://joxi.ru/Y2LyYoMCnwxLgA
ф
А вот непохожие выдают все корректно: http://joxi.ru/E2pV1xKIBOvXKr

**Comment by webber12** [comment]
Есть подозрение, что для данного фильтра в настройке стоит птичка "Множественный" - эта птичка используется в случае, если у ТВ может быть несколько вариантов одновременно. Они в базе хранятся в виде вариант1||вариант2||вариант3 и кроме как через like их и не найти. Но в вашем случае модель может быть одна, соответственно птичку "множественный" надо снять и оно будет искать не по лайку, а по полному вхождению.
